### ISSUE TITLE
Gemmi CIF parser

### ISSUE THREAD

**Issue by wojdyr** [chemfiles/cifxx#1]
That's not a real issue.
I just came across this new project and wanted to say hi, I'm also in the business of writing modern, header only, C++11 CIF files parser:
https://github.com/project-gemmi/gemmi/
The whole project is in early stage - just started this year, but the CIF parser is the most mature part of it.

**Comment by Luthaf** [comment]
Thank you, your project looks interesting! 

I need a CIF parser for [chemfiles](https://github.com/chemfiles/chemfiles), which is BSD licensed, so I can not use your code there: LGPL is roughly equivalent to GPL when working with header only library, as is it very hard to allow users to relink the code.

But maybe we could collaborate on this, and have a single code base providing CIF parsing?

----

BTW, I've seen you are writing a JS molecular viewer, so you might be interested by chemfiles: it is a library that offers reading and writing chemistry simulation files. I have a branch compiling it to ASM.js/Webassembly using emscripten: https://github.com/chemfiles/chemfiles/tree/emscripten. It would give you access to more formats directly in the browser =)

**Comment by wojdyr** [comment]
I'd love to collaborate on this, but it'd be the same problem with licensing (what I'd wrote would be copyrighted by my employer).
Actually I tried (and failed) to convinced other people involved in this project to pick a more liberal license. I'll try again at some point. We considered the Apache License. Would it work for you?

**Comment by Luthaf** [comment]
Yes, Apache would work =). I think this license is appreciated by companies due to its patent clause.

And maybe the fact that there is a collaboration opportunity could change the mind of others!
